### ISSUE TITLE
Flight Master World Map background

### ISSUE THREAD

**Issue by Goregrin** [ElvUI-Cataclysm/ElvUI-4.3.4#18]
Hello,
most of the time there is no background for the world map at the Flight Master. (Appears black with Flight paths).

**Comment by Apollyonn** [comment]
i think i fixed it 2 days ago commit 5153843ef319e7289616ab8c426a87db9bd917e9 , are you using the latest version?

**Comment by Goregrin** [comment]
I dont. Will download and test, thanks :)
