### ISSUE TITLE
Characters default animation is "holding map"

### ISSUE THREAD

**Issue by IamR00l** [ElvUI-Cataclysm/ElvUI-4.3.4#26]
When I login, or create any character, all of my characters are doing the animation as if you are looking at the map. I have confirmed this only happens when ELVUI is enabled, and have even cleared out account folders, as well as downloaded other clients.

Here are pics to show:

https://imgur.com/a/d2bBN

**Comment by Apollyonn** [comment]
Can't reproduce, most likely its a server side issue.
