### ISSUE TITLE
elvui conflict with gm genie

### ISSUE THREAD

**Issue by TheRealestMcCoy** [ElvUI-Cataclysm/ElvUI-4.3.4#27]
So there is a conflict with the cata elvui when running gm genie.
GM genie is a GM addon to help track tickets. 
With elvui enabled the ticket window does not draw a list of tickets as it should. Half the commands are messed up.

**Comment by TheRealestMcCoy** [comment]
@Apollyonn if you need more info i can give it to you but im not sure what the actual cause is.

**Comment by Apollyonn** [comment]
any lua errors?

**Comment by TheRealestMcCoy** [comment]
no

**Comment by TheRealestMcCoy** [comment]
so i dont know where to even tell you to look for the issue. But its elvui i turned off all the addons only had gm genie on it worked turned elvui on it broke again. Turned elvui off and all other addons back on gm geneie still worked

**Comment by TheRealestMcCoy** [comment]
gm genie elvui off https://gyazo.com/4c4f0bde4e948746438bb4ce7bb92e86
elvui on https://gyazo.com/ee10329d8e21e548283ab746a9d361fd

**Comment by TheRealestMcCoy** [comment]
[GMGenie.zip](https://github.com/ElvUI-Cataclysm/ElvUI-4.3.4/files/1361450/GMGenie.zip)
here is the copy of gm genie if you need to see or dissect anything

**Comment by Apollyonn** [comment]
disable chat module and try if addon works

**Comment by TheRealestMcCoy** [comment]
yes i disabled the chat and it worked 
https://gyazo.com/e42ac1524a798d4baa42b883e17b0822

Chat enabled 
https://gyazo.com/d22818b5b42dcd7d69588f6fbbea0674

**Comment by Apollyonn** [comment]
I'm not sure when or if i can fix this.
