### ISSUE TITLE
Aura Bars never show Bone Shield buff.

### ISSUE THREAD

**Issue by Audisek** [ElvUI-Cataclysm/ElvUI-4.3.4#29]
This happened after I updated from 1.27 to 1.28
Maybe it doesn't work for any buffs with stacks?

**Comment by Apollyonn** [comment]
Set maximun duration to 5 minutes if you want bone shield to show. Default duration for aura bars to show is 2 minutes.

**Comment by Audisek** [comment]
Thank you! I'm so stupid I didn't notice the option. 😄
