### ISSUE TITLE
Nameplates

### ISSUE THREAD

**Issue by brolio** [ElvUI-Cataclysm/ElvUI-4.3.4#38]
With the new update the background glow around nameplates when it gets targeted goes over the nameplate's borders, it fixes itself when you right click to move the camera though.

**Comment by Apollyonn** [comment]
https://gyazo.com/4aa9eb2d08a56f34dd89fade37b5035e
??

**Comment by Apollyonn** [comment]
Set Multisampling to 1
![1111](https://user-images.githubusercontent.com/19589902/36228145-1a899af8-11dc-11e8-89f8-e0602573d218.png)

**Comment by brolio** [comment]
this i what i was referring to
[https://imgur.com/a/bB0tu](url)
by the way i have set multisampling to 1x
