### ISSUE TITLE
Buff font doesnt change size

### ISSUE THREAD

**Issue by lierox90** [ElvUI-Cataclysm/ElvUI-4.3.4#41]
Hi, there is issue with font size for Buff/Debuff indicator, despite of change timer bellow buff doesnt react

![image](https://user-images.githubusercontent.com/4543689/38467867-52c2939e-3b3e-11e8-92b2-7d0662f22d86.png)

![image](https://user-images.githubusercontent.com/4543689/38467873-5bf4e1ba-3b3e-11e8-9131-27aead6aacec.png)

**Comment by Apollyonn** [comment]
![c09e4c8ef434ffcda02462c1945ab5b0](https://user-images.githubusercontent.com/19589902/38484306-cff52476-3bde-11e8-8b62-89b0557d72b5.png)
