### ISSUE TITLE
Bug with Libraries

### ISSUE THREAD

**Issue by Dokho0** [ElvUI-Cataclysm/ElvUI-4.3.4#47]
**Description**
Bug with libraries on some addons.
Examples : Skada,Gathermate2,Omen3 

**Version Number**
2.0

**Steps to Reproduce**
When activated or installed

**Only ElvUI Enabled**
No

**Additional Information**
The same bug in all language.

**Error Log**

```
1x AceLocale-3.0-7: Skada: Missing entry for "esES"
Libraries\Ace3\AceLocale-3.0\AceLocale-3.0-7.lua:129: in function "NewLocale"
Skada-1.4-2\locale\esES-Castellano (Europa).lua:1: in main chunk

Locals:
nil

```

**Comment by Apollyonn** [comment]
check now

**Comment by Dokho0** [comment]
Thanks, now it works !! :D
