### ISSUE TITLE
Shift + Click and Tooltip placement

### ISSUE THREAD

**Issue by Lemonadez** [ElvUI-Cataclysm/ElvUI-4.3.4#50]
When I was holding shift and click another player.. I get this error.

> 3x Blizzard_InspectUI\InspectGuildFrame.lua:18: Usage: GetGuildInfo("unit")
> <in C code>
> Blizzard_InspectUI\InspectGuildFrame.lua:18: in function "InspectGuildFrame_Update"
> Blizzard_InspectUI\InspectGuildFrame.lua:8: in function <Blizzard_InspectUI\InspectGuildFrame.lua:6>

As for tooltip. I wanted to move it. But I cant find the tooltip anchors when I toggle anchor or /moveui
I can only do on tooltip anchor it to mouse :(

**Comment by Apollyonn** [comment]
Its blizzard UI bug. Use this https://www.wowace.com/projects/inspectfix/files/593021

**Comment by Lemonadez** [comment]
Now I find how to move the tooltip anchor.
![image](https://user-images.githubusercontent.com/19479119/74272273-5d4c0280-4cdc-11ea-8fb5-8d99e8ce2f85.png)

You cant click on tooltip bcuz of Right Chat Panel blocking it.
Only way to move it was Chat->Separate Panel-> Decrease Right Panel Width. Then You can click on Tooltip at the bottom right corner  ^_^

**Comment by Apollyonn** [comment]
![123](https://user-images.githubusercontent.com/19589902/74272598-96559880-4d17-11ea-818a-b69261eb241d.jpg)

**Comment by Crumdidlyumshis** [comment]
![img](https://media0.giphy.com/media/mBjulVQHWumozyk6O2/source.gif)
