### ISSUE TITLE
Keybind mode no longer works. Bar 7 action bar binds dont work.

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-Cataclysm/ElvUI-4.3.4#52]
Recently updated to the very latest version released today (I keep my ElvUI up to date) -- After logging back in, every ability on my bar 7 does not work unless I click it (keys dont register) but other bars work fine.

Also unable to enter keybind mode via /kb or manually pressing the "Keybind Mode" button in the elvui settings window.

Another thing: Changing visibility states doesn't take effect unless you reload or toggle mouseover on/off.

**Comment by Apollyonn** [comment]
![333](https://user-images.githubusercontent.com/19589902/74487272-b6c45500-4ec7-11ea-9461-69ac7c20432f.gif)
Can't reproduce.

**Comment by Triksterism** [comment]
Weird. I reverted back to 2.3 and everything works properly again.
