### ISSUE TITLE
Buffs/Debuffs dont keep their text sizes

### ISSUE THREAD

**Issue by Triksterism** [ElvUI-Cataclysm/ElvUI-4.3.4#56]
Video: https://imgur.com/JC0Kp57

**Comment by Apollyonn** [comment]
What do you mean they don't keep their size? In the video you show, they work as they should.

**Comment by Triksterism** [comment]
In the video they start at the same size they end on in the config. However the text is a different size at the start than at the end despite being the same setting.

**Comment by Apollyonn** [comment]
![test](https://user-images.githubusercontent.com/19589902/74977980-6e131b80-5434-11ea-99c3-9a1f5959836c.gif)

**Comment by Apollyonn** [comment]
fixed
