### ISSUE TITLE
Cast bar disappears with channelled ability attempted recast.

### ISSUE THREAD

**Issue by nullKomplex** [ElvUI-Cataclysm/ElvUI-4.3.4#57]
## Describe the bug
When attempting to cast a channeled ability that is currently active and on cooldown, the cast bar disappears.

**Do you have an error log of what happened?**
There are no errors.

### To Reproduce
1. Begin casting Penance on any target.
2. Press the button for Penance again at any time during the channel.
3. Observe as cast bar disappears until next cast.

**Screenshots**
https://streamable.com/b8wox

**Did you try having ElvUI as the only enabled addon and everything else disabled?**
Yes. Only ElvUI and ElvUI_Options were enabled in the video above.

**Which version of ElvUI are you using?**
08cad02

### Additional Info

This appears to be caused by a `UNIT_SPELLCAST_FAILED` event being sent in the event of `Not yet recovered`. As this event is indistinguishable from a standard failed event, you will likely need to move the system over to the Combat Log for more verbose fails, where one of the args contains messages such as "Not yet recovered".

**Comment by CraftedRO** [comment]
Confirm
![WoWScrnShot_022120_163226](https://user-images.githubusercontent.com/24683355/75043104-276f0100-54c8-11ea-9172-6e987a57c4c4.jpg)

**Comment by Apollyonn** [comment]
I think it should be ok, let me know if you have more problems with it.
