### ISSUE TITLE
Exception thrown after update

### ISSUE THREAD

**Issue by argothus** [ElvUI-Cataclysm/ElvUI-4.3.4#60]
I just replaced the two folders and logged in. I did the install routine once again.

`Date: 2020-03-17 08:43:15
ID: 1
Error occured in: Global
Count: 1
Message: ...rface\AddOns\ElvUI\Modules\Skins\Blizzard\Talent.lua line 133:
   attempt to index a nil value
Debug:
   (tail call): ?
   ...rface\AddOns\ElvUI\Modules\Skins\Blizzard\Talent.lua:133: SkinTalents()
   ...rface\AddOns\ElvUI\Modules\Skins\Blizzard\Talent.lua:158:
      ...rface\AddOns\ElvUI\Modules\Skins\Blizzard\Talent.lua:10
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ElvUI\Modules\Skins\Skins.lua:825: Initialize()
   ElvUI\Modules\Skins\Skins.lua:834:
      ElvUI\Modules\Skins\Skins.lua:833
   ...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:157:
      ...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:157
   [string "safecall Dispatcher[1]"]:4:
      [string "safecall Dispatcher[1]"]:4
   [C]: ?
   [string "safecall Dispatcher[1]"]:13: ?()
   ...der\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:92: Fire()
   ElvUI\Core\Core.lua:1061: CallLoadedModule()
   ElvUI\Core\Core.lua:1086: InitializeModules()
   ElvUI\Core\Core.lua:1284: Initialize()
   ElvUI\Init.lua:230:
      ElvUI\Init.lua:229
AddOns:
  Swatter, v3.3.0 (<%codename%>)
  AtlasLootLoader, vv6.05.04
  AucAdvanced, v5.13.5258 (BoldBandicoot)
  AucFilterBasic, v5.13.5258 (BoldBandicoot)
  AucFilterOutlier, v5.13.5258.5187(5.13/embedded)
  AucMatchUndercut, v5.13.5258.5232(5.13/embedded)
  AucStatHistogram, v5.13.5258 (BoldBandicoot)
  AucStatiLevel, v5.13.5258 (BoldBandicoot)
  AucStatPurchased, v5.13.5258 (BoldBandicoot)
  AucStatSales, v5.13.5258.4838(5.13/embedded)
  AucStatSimple, v5.13.5258 (BoldBandicoot)
  AucStatStdDev, v5.13.5258 (BoldBandicoot)
  AucStatWOWEcon, v5.13.5258.4828(5.13/embedded)
  AucUtilAHWindowControl, v5.13.5258.5133(5.13/embedded)
  AucUtilAppraiser, v5.13.5258.5241(5.13/embedded)
  AucUtilAskPrice, v5.13.5258.5160(5.13/embedded)
  AucUtilAutoMagic, v5.13.5258.5224(5.13/embedded)
  AucUtilCompactUI, v5.13.5258.5254(5.13/embedded)
  AucUtilEasyBuyout, v5.13.5258.5241(5.13/embedded)
  AucUtilFixAH, v5.13.5258 (BoldBandicoot)
  AucUtilItemSuggest, v5.13.5258.5224(5.13/embedded)
  AucUtilPriceLevel, v5.13.5258.5241(5.13/embedded)
  AucUtilScanButton, v5.13.5258.5153(5.13/embedded)
  AucUtilScanFinish, v5.13.5258.5153(5.13/embedded)
  AucUtilScanProgress, v5.13.5258.4979(5.13/embedded)
  AucUtilScanStart, v5.13.5258.5153(5.13/embedded)
  AucUtilSearchUI, v5.13.5258.5254(5.13/embedded)
  AucUtilSimpleAuction, v5.13.5258.5210(5.13/embedded)
  AucUtilVendMarkup, v5.13.5258.4828(5.13/embedded)
  Babylonian, v5.1.DEV.312(/embedded)
  BeanCounter, v5.13.5258 (BoldBandicoot)
  Configator, v5.1.DEV.323(/embedded)
  DBMCore, v
  DebugLib, v5.1.DEV.312(/embedded)
  ElvUI, v2.7
  Enchantrix, v5.13.5258 (BoldBandicoot)
  EnchantrixBarker, v5.13.5258 (BoldBandicoot)
  FishingBuddy, v1.0.8b
  Gatherer, v3.3.0
  Informant, v5.13.5258 (BoldBandicoot)
  LibExtraTip, v5.12.DEV.319(/embedded)
  Recount, v
  SlideBar, v3.3.0 (<%codename%>)
  Stubby, v5.13.5258 (BoldBandicoot)
  TipHelper, v5.12.DEV.315(/embedded)
  WIM, v3.5.9
  ZygorGuidesViewer, v3.3
  ZygorTalentAdvisor, v2.0.240
  BlizRuntimeLib_enUS v4.3.4.40300 <login.apollo-wow.com>
  (ck=7fa)`

**Comment by Apollyonn** [comment]
Can't reproduce. Under what circumstances this error occured? Also are you using any addons thats altering your talent ui?

**Comment by argothus** [comment]
probably because i use the zygor addon and this addon got a talent advisor. in this case i'll close it. thanks for your work.
