### ISSUE TITLE
 Mouseover inspect error

### ISSUE THREAD

**Issue by Kilokambala** [ElvUI-Cataclysm/ElvUI-4.3.4#61]
I get some error when I try inspect someone using shift+mouseover.

Date: 2020-03-23 18:32:18
ID: 1
Error occured in: Global
Count: 1
Message: ...face\AddOns\Blizzard_InspectUI\InspectGuildFrame.lua line 18:
   Usage: GetGuildInfo("unit")
Debug:
   [C]: ?
   [C]: GetGuildInfo()
   ...face\AddOns\Blizzard_InspectUI\InspectGuildFrame.lua:18: InspectGuildFrame_Update()
   ...face\AddOns\Blizzard_InspectUI\InspectGuildFrame.lua:8:
      ...face\AddOns\Blizzard_InspectUI\InspectGuildFrame.lua:6
AddOns:
  Swatter, v3.3.0 (<%codename%>)
  ACP, vr154 
  DebugLib, v5.1.DEV.312(/embedded)
  ElvUI, v2.7
  ElvUIAddOnSkins, v1.2
  ElvUIEnhanced, v1.4
  ElvUIEnhancedFriendsList, v1.10
  ElvUIMicrobarEnhancement, v1.1
  LibBabbleDigSites30, vr21
  SlideBar, v3.3.0 (<%codename%>)
  Stubby, v5.13.5258 (BoldBandicoot)
  BlizRuntimeLib_ruRU v4.3.4.40300 <logon.circle-servers.com>
  (ck=173)

**Comment by Apollyonn** [comment]
It's blizzard bug, use this to fix it. https://www.wowace.com/projects/inspectfix/files/593021

**Comment by Kilokambala** [comment]
Thx u
