### ISSUE TITLE
Filters problem

### ISSUE THREAD

**Issue by brolio** [ElvUI-Cataclysm/ElvUI-4.3.4#64]
Whenever i even by accident touch the filters dropdown menu every other page in the settings gets blank or almost empty
It resolves itself by reloading the ui
![Senza titolo](https://user-images.githubusercontent.com/32934191/80770554-e5f67400-8b50-11ea-85e5-8cb8edd07b63.png)

**Comment by Apollyonn** [comment]
Ace3 gui conflict.
One of your other addons is causing it.
