### ISSUE TITLE
Debuff doesn't show in frames

### ISSUE THREAD

**Issue by Sammy974** [ElvUI-Cataclysm/ElvUI-4.3.4#65]
As tank, I need to see the debuffs in the target of target frame, but it doesn't show up, also if I activate them in the options panel. I can see them with "show aura" while I'm setting them, but during the fight no debuff are shown. Same in the focus target. Debuff are not blacklisted because they're raid debuff and they're all supposed to be shown in frames. Can you help me?

**Comment by Apollyonn** [comment]
![WoWScrnShot_061320_090056](https://user-images.githubusercontent.com/19589902/84561387-93fe5c00-ad54-11ea-8459-cd2904b10fa5.jpg)
works fine for me

**Comment by Apollyonn** [comment]
Also try to remove all filters and see if that suits you better.
