### ISSUE TITLE
Chat-Bar Hovers Armor/Durability/Defense-Bar

### ISSUE THREAD

**Issue by Phoenix9867** [ElvUI-Cataclysm/ElvUI-4.3.4#68]
In Previous Versions, when messege was send in chat, the typing bar was hidden behind the bar showing Armor/Durabilty/Defense after, now it stays above.
![issue](https://user-images.githubusercontent.com/41048358/100847284-e9076900-347f-11eb-858d-f84e5391b235.PNG)

Only reloading seems to fix this:
![asItShouldBe](https://user-images.githubusercontent.com/41048358/100847386-0f2d0900-3480-11eb-896a-1bed6c76502f.PNG)

From my point of view, everytime executing /reload when finished texting ingame, is really annoying.

**Comment by Apollyonn** [comment]
Go to interface/Social and change chat style to classic, IM style not supported.
![style](https://user-images.githubusercontent.com/19589902/111858800-61693b80-8944-11eb-8e2f-b7634c9dc912.jpg)
