### ISSUE TITLE
Tooltip Anchor

### ISSUE THREAD

**Issue by Aemrodd** [ElvUI-Cataclysm/ElvUI-4.3.4#72]
Tooltip Anchor can't be accessed. When moving the chat anchor, the tooltip anchor is bound to it

![WoWScrnShot_091521_132503](https://user-images.githubusercontent.com/58418019/133425119-4aa1b840-06f7-48bd-99c4-02b19beeb451.jpg)

**Comment by Apollyonn** [comment]
![1](https://user-images.githubusercontent.com/19589902/145595943-8a9b0e68-f202-4ac7-ae63-751e4e2c1c62.jpg)
